### ISSUE TITLE
Module build failed error

### ISSUE THREAD

**Issue by teod** [coderas/babel-plugin-jsx-remove-qa#3]
I am getting an error when trying to use the plugin

```
ERROR in ./index.js
Module build failed: /[PROJECT_FOLDER_PATH]/node_modules/babel-plugin-jsx-remove-qa/index.js:75
export default RemoveQAClasses;
^^^^^^
SyntaxError: Unexpected token export
```

I have in my .babelrc set this:
```
      "plugins": [
        "babel-plugin-jsx-remove-qa",
        {
            "attributes": ["cssClassName"]
        }
      ],
```

**Comment by coderas** [comment]
Do you have a node version you could share ? You will need to transpile for module support in node. https://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/
Let me know if you still have issues.
